In [1]:
import pandas as pd
import requests

In [4]:
aus_url = 'http://popdata.unhcr.org/api/stats/asylum_seekers_monthly.json?year=2015,2016&month=8&coa=FRA&coo=SYR'

In [5]:
data = requests.get(aus_url)
data.content

b'[{"country_of_asylum":"FRA","country_of_asylum_en":"France","country_of_origin":"SYR","country_of_origin_en":"Syrian Arab Rep.","year":2015,"month":8,"month_en":"August","value":322}]'

In [4]:
stats  = data.content.decode("utf-8")

In [5]:
import json 
stats = json.loads(data.content)
print([json.dumps(stats)])

['[{"country_of_asylum": "SRB", "country_of_asylum_en": "Serbia and Kosovo: S/RES/1244 (1999)", "country_of_origin": "SYR", "country_of_origin_en": "Syrian Arab Rep.", "year": 2015, "month": 8, "month_en": "August", "value": 3}]']

In [6]:
pd.read_json('http://popdata.unhcr.org/api/stats/resettlement.json?year=2014&country_of_asylum=AUS')

,country_of_asylum,country_of_asylum_en,country_of_origin,country_of_origin_en,value,year
0,AUS,Australia,AFG,Afghanistan,1874,2014
1,AUS,Australia,ARE,United Arab Emirates,10,2014
2,AUS,Australia,BDI,Burundi,48,2014
3,AUS,Australia,BEN,Benin,3,2014
4,AUS,Australia,BTN,Bhutan,315,2014
5,AUS,Australia,CHN,China,4,2014
6,AUS,Australia,CIV,CÃ´te d'Ivoire,28,2014
7,AUS,Australia,COD,Dem. Rep. of the Congo,216,2014
8,AUS,Australia,COG,Congo,3,2014
9,AUS,Australia,DJI,Djibouti,6,2014
10,AUS,Australia,DZA,Algeria,1,2014
11,AUS,Australia,EGY,Egypt,105,2014
12,AUS,Australia,ERI,Eritrea,277,2014
13,AUS,Australia,ETH,Ethiopia,176,2014
14,AUS,Australia,GHA,Ghana,6,2014
15,AUS,Australia,GIN,Guinea,14,2014
16,AUS,Australia,IDN,Indonesia,10,2014
17,AUS,Australia,IND,India,191,2014
18,AUS,Australia,IRN,Iran (Islamic Rep. of),739,2014
19,AUS,Australia,IRQ,Iraq,2335,2014
20,AUS,Australia,JOR,Jordan,20,2014
21,AUS,Australia,KEN,Kenya,47,2014
22,AUS,Australia,KWT,Kuwait,12,2014
23,AUS,Australia,LBN,Lebanon,65,2014
24,AUS,Australia,LBR,Liberia,59,2014
25,AUS,Australia,LBY,Libya,8,2014
26,AUS,Australia,LKA,Sri Lanka,20,2014
27,AUS,Australia,MMR,Myanmar,1292,2014
28,AUS,Australia,MWI,Malawi,4,2014
29,AUS,Australia,MYS,Malaysia,144,2014
30,AUS,Australia,NPL,Nepal,223,2014
31,AUS,Australia,PAK,Pakistan,325,2014
32,AUS,Australia,PSE,Palestinian,4,2014
33,AUS,Australia,RWA,Rwanda,10,2014
34,AUS,Australia,SAU,Saudi Arabia,11,2014
35,AUS,Australia,SDN,Sudan,128,2014
36,AUS,Australia,SLE,Sierra Leone,48,2014
37,AUS,Australia,SOM,Somalia,186,2014
38,AUS,Australia,SSD,South Sudan,115,2014
39,AUS,Australia,SYR,Syrian Arab Rep.,1820,2014
40,AUS,Australia,TGO,Togo,7,2014
41,AUS,Australia,THA,Thailand,434,2014
42,AUS,Australia,TIB,Tibetan,109,2014
43,AUS,Australia,TUR,Turkey,18,2014
44,AUS,Australia,TZA,United Rep. of Tanzania,9,2014
45,AUS,Australia,UGA,Uganda,51,2014
46,AUS,Australia,VEN,Venezuela (Bolivarian Republic of),1,2014
47,AUS,Australia,VNM,Viet Nam,1,2014
48,AUS,Australia,ZAF,South Africa,9,2014
49,AUS,Australia,ZMB,Zambia,20,2014
50,AUS,Australia,ZWE,Zimbabwe,9,2014

In [7]:
pd.read_json('http://popdata.unhcr.org/api/stats/resettlement.json?year=2014&country_of_asylum=USA')

,country_of_asylum,country_of_asylum_en,country_of_origin,country_of_origin_en,value,year
0,USA,United States of America,AFG,Afghanistan,696,2014
1,USA,United States of America,ARM,Armenia,45,2014
2,USA,United States of America,AZE,Azerbaijan,21,2014
3,USA,United States of America,BDI,Burundi,133,2014
4,USA,United States of America,BGD,Bangladesh,2,2014
5,USA,United States of America,BLR,Belarus,60,2014
6,USA,United States of America,BTN,Bhutan,7476,2014
7,USA,United States of America,CAF,Central African Rep.,200,2014
8,USA,United States of America,CHN,China,50,2014
9,USA,United States of America,CIV,CÃ´te d'Ivoire,39,2014
10,USA,United States of America,CMR,Cameroon,9,2014
11,USA,United States of America,COD,Dem. Rep. of the Congo,5128,2014
12,USA,United States of America,COG,Congo,58,2014
13,USA,United States of America,COL,Colombia,461,2014
14,USA,United States of America,CUB,Cuba,3703,2014
15,USA,United States of America,ECU,Ecuador,23,2014
16,USA,United States of America,EGY,Egypt,17,2014
17,USA,United States of America,ERI,Eritrea,1409,2014
18,USA,United States of America,ETH,Ethiopia,687,2014
19,USA,United States of America,GAB,Gabon,3,2014
20,USA,United States of America,GBR,United Kingdom of Great Britain and Northern I...,1,2014
21,USA,United States of America,GEO,Georgia,15,2014
22,USA,United States of America,GHA,Ghana,2,2014
23,USA,United States of America,GIN,Guinea,10,2014
24,USA,United States of America,GMB,Gambia,1,2014
25,USA,United States of America,HTI,Haiti,4,2014
26,USA,United States of America,IDN,Indonesia,18,2014
27,USA,United States of America,IND,India,23,2014
28,USA,United States of America,IRN,Iran (Islamic Rep. of),2830,2014
29,USA,United States of America,IRQ,Iraq,20337,2014
...,...,...,...,...,...,...
41,USA,United States of America,MAR,Morocco,1,2014
42,USA,United States of America,MKD,The former Yugoslav Rep. of Macedonia,241,2014
43,USA,United States of America,MLI,Mali,2,2014
44,USA,United States of America,MMR,Myanmar,15971,2014
45,USA,United States of America,MRT,Mauritania,4,2014
46,USA,United States of America,NPL,Nepal,126,2014
47,USA,United States of America,PAK,Pakistan,229,2014
48,USA,United States of America,PHL,Philippines,4,2014
49,USA,United States of America,PRK,Dem. People's Rep. of Korea,15,2014
50,USA,United States of America,PSE,Palestinian,140,2014
51,USA,United States of America,RUS,Russian Federation,198,2014
52,USA,United States of America,RWA,Rwanda,51,2014
53,USA,United States of America,SAU,Saudi Arabia,2,2014
54,USA,United States of America,SDN,Sudan,1043,2014
55,USA,United States of America,SGP,Singapore,3,2014
56,USA,United States of America,SLE,Sierra Leone,10,2014
57,USA,United States of America,SOM,Somalia,10057,2014
58,USA,United States of America,SYR,Syrian Arab Rep.,271,2014
59,USA,United States of America,TCD,Chad,31,2014
60,USA,United States of America,TGO,Togo,25,2014
61,USA,United States of America,THA,Thailand,8,2014
62,USA,United States of America,TKM,Turkmenistan,2,2014
63,USA,United States of America,TUN,Tunisia,2,2014
64,USA,United States of America,UGA,Uganda,22,2014
65,USA,United States of America,UKR,Ukraine,667,2014
66,USA,United States of America,UZB,Uzbekistan,65,2014
67,USA,United States of America,VNM,Viet Nam,80,2014
68,USA,United States of America,YEM,Yemen,14,2014
69,USA,United States of America,ZAF,South Africa,3,2014
70,USA,United States of America,ZWE,Zimbabwe,3,2014

In [8]:
pd.read_json('http://popdata.unhcr.org/api/stats/resettlement.json?year=2014&country_of_asylum=DEU')

,country_of_asylum,country_of_asylum_en,country_of_origin,country_of_origin_en,value,year
0,DEU,Germany,AFG,Afghanistan,16,2014
1,DEU,Germany,CHN,China,3,2014
2,DEU,Germany,ETH,Ethiopia,1,2014
3,DEU,Germany,IRN,Iran (Islamic Rep. of),6,2014
4,DEU,Germany,IRQ,Iraq,103,2014
5,DEU,Germany,LKA,Sri Lanka,59,2014
6,DEU,Germany,SDN,Sudan,2,2014
7,DEU,Germany,SOM,Somalia,31,2014
8,DEU,Germany,SSD,South Sudan,1,2014
9,DEU,Germany,STA,Stateless,58,2014

In [14]:
df = pd.read_json('http://popdata.unhcr.org/api/stats/resettlement.json?year=2014&country_of_asylum=FRA')

In [15]:
df

,country_of_asylum,country_of_asylum_en,country_of_origin,country_of_origin_en,value,year
0,FRA,France,AFG,Afghanistan,18,2014
1,FRA,France,BDI,Burundi,1,2014
2,FRA,France,CAF,Central African Rep.,1,2014
3,FRA,France,CIV,CÃ´te d'Ivoire,4,2014
4,FRA,France,COD,Dem. Rep. of the Congo,12,2014
5,FRA,France,COG,Congo,1,2014
6,FRA,France,ETH,Ethiopia,4,2014
7,FRA,France,IRN,Iran (Islamic Rep. of),1,2014
8,FRA,France,IRQ,Iraq,2,2014
9,FRA,France,KAZ,Kazakhstan,1,2014
10,FRA,France,LKA,Sri Lanka,3,2014
11,FRA,France,NPL,Nepal,1,2014
12,FRA,France,PSE,Palestinian,3,2014
13,FRA,France,RUS,Russian Federation,3,2014
14,FRA,France,RWA,Rwanda,7,2014
15,FRA,France,SDN,Sudan,2,2014
16,FRA,France,SOM,Somalia,5,2014
17,FRA,France,SYR,Syrian Arab Rep.,40,2014
18,FRA,France,TCD,Chad,1,2014

In [12]:
import arcgis
from arcgis.gis import GIS
from IPython.display import display

In [13]:
gis = GIS("http://slustl.maps.arcgis.com/home", "gregbrunner_slugis")

Enter password: Â·Â·Â·Â·Â·Â·Â·Â·

In [16]:
resettlment_stats = gis.content.import_data(df, {"Address" : "country_of_origin_en"})

In [17]:
map  =  gis.map('England', zoomlevel=7)
map

MapView(basemaps=['dark-gray', 'dark-gray-vector', 'gray', 'gray-vector', 'hybrid', 'national-geographic', 'ocâ¦

In [18]:
map.add_layer(resettlment_stats, { "renderer":"ClassedSizeRenderer", "field_name":"value" })

In [21]:
resettlment_stats.query().df

,ObjectId,country_of_asylum,country_of_asylum_en,country_of_origin,country_of_origin_en,value,year,SHAPE
0,1,FRA,France,AFG,Afghanistan,18,2014,"{'x': 7349837.296999998, 'y': 4006150.33429999..."
1,2,FRA,France,BDI,Burundi,1,2014,"{'x': 3331396.2041000016, 'y': -370044.6110999..."
2,3,FRA,France,CAF,Central African Rep.,1,2014,"{'x': -6410163.564099999, 'y': -2919775.608100..."
3,4,FRA,France,CIV,CÃ´te d'Ivoire,4,2014,"{'x': -618349.5579000004, 'y': 851797.52149999..."
4,5,FRA,France,COD,Dem. Rep. of the Congo,12,2014,"{'x': 2628888.2291, 'y': -318749.5758000016, '..."
5,6,FRA,France,COG,Congo,1,2014,"{'x': 1695985.2120000012, 'y': -91481.61540000..."
6,7,FRA,France,ETH,Ethiopia,4,2014,"{'x': 4413233.397100002, 'y': 963111.951699998..."
7,8,FRA,France,IRN,Iran (Islamic Rep. of),1,2014,"{'x': 4481939.772300001, 'y': 5004042.44370000..."
8,9,FRA,France,IRQ,Iraq,2,2014,"{'x': 4873252.5419000015, 'y': 3900478.3422999..."
9,10,FRA,France,KAZ,Kazakhstan,1,2014,"{'x': 7480118.2469, 'y': 6137371.416599996, 's..."
10,11,FRA,France,LKA,Sri Lanka,3,2014,"{'x': 8983330.668499999, 'y': 850505.467399999..."
11,12,FRA,France,NPL,Nepal,1,2014,"{'x': 9344621.5324, 'y': 3281684.584399998, 's..."
12,13,FRA,France,PSE,Palestinian,3,2014,"{'x': 3918967.5766000003, 'y': 3751859.3574, '..."
13,14,FRA,France,RUS,Russian Federation,3,2014,"{'x': 10776324.665199999, 'y': 8856659.7117, '..."
14,15,FRA,France,RWA,Rwanda,7,2014,"{'x': 3334721.4657999985, 'y': -222505.4270999..."
15,16,FRA,France,SDN,Sudan,2,2014,"{'x': 3340607.6521999985, 'y': 1810890.7159999..."
16,17,FRA,France,SOM,Somalia,5,2014,"{'x': 5143306.1217, 'y': 490803.27809999883, '..."
17,18,FRA,France,TCD,Chad,1,2014,"{'x': 2078798.6218999997, 'y': 1732601.8244000..."

In [22]:
sdf = resettlment_stats.query().df

In [23]:
reset_map = gis.content.import_data(sdf, title='UNHCR Resettlements in France')

TypeError: object of type 'bool' has no len()

TypeError: object of type 'bool' has no len()

TypeError: object of type 'bool' has no len()

In [1]:
new_map = gis.map()
new_map

NameError: name 'gis' is not defined

In [27]:
new_map.add_layer(reset_map, { "renderer":"ClassedSizeRenderer", "field_name":"value" })

In [28]:
usa_df = pd.read_json('http://popdata.unhcr.org/api/stats/resettlement.json?year=2014&country_of_asylum=USA')

In [29]:
usa_df

,country_of_asylum,country_of_asylum_en,country_of_origin,country_of_origin_en,value,year
0,USA,United States of America,AFG,Afghanistan,696,2014
1,USA,United States of America,ARM,Armenia,45,2014
2,USA,United States of America,AZE,Azerbaijan,21,2014
3,USA,United States of America,BDI,Burundi,133,2014
4,USA,United States of America,BGD,Bangladesh,2,2014
5,USA,United States of America,BLR,Belarus,60,2014
6,USA,United States of America,BTN,Bhutan,7476,2014
7,USA,United States of America,CAF,Central African Rep.,200,2014
8,USA,United States of America,CHN,China,50,2014
9,USA,United States of America,CIV,CÃ´te d'Ivoire,39,2014
10,USA,United States of America,CMR,Cameroon,9,2014
11,USA,United States of America,COD,Dem. Rep. of the Congo,5128,2014
12,USA,United States of America,COG,Congo,58,2014
13,USA,United States of America,COL,Colombia,461,2014
14,USA,United States of America,CUB,Cuba,3703,2014
15,USA,United States of America,ECU,Ecuador,23,2014
16,USA,United States of America,EGY,Egypt,17,2014
17,USA,United States of America,ERI,Eritrea,1409,2014
18,USA,United States of America,ETH,Ethiopia,687,2014
19,USA,United States of America,GAB,Gabon,3,2014
20,USA,United States of America,GBR,United Kingdom of Great Britain and Northern I...,1,2014
21,USA,United States of America,GEO,Georgia,15,2014
22,USA,United States of America,GHA,Ghana,2,2014
23,USA,United States of America,GIN,Guinea,10,2014
24,USA,United States of America,GMB,Gambia,1,2014
25,USA,United States of America,HTI,Haiti,4,2014
26,USA,United States of America,IDN,Indonesia,18,2014
27,USA,United States of America,IND,India,23,2014
28,USA,United States of America,IRN,Iran (Islamic Rep. of),2830,2014
29,USA,United States of America,IRQ,Iraq,20337,2014
...,...,...,...,...,...,...
41,USA,United States of America,MAR,Morocco,1,2014
42,USA,United States of America,MKD,The former Yugoslav Rep. of Macedonia,241,2014
43,USA,United States of America,MLI,Mali,2,2014
44,USA,United States of America,MMR,Myanmar,15971,2014
45,USA,United States of America,MRT,Mauritania,4,2014
46,USA,United States of America,NPL,Nepal,126,2014
47,USA,United States of America,PAK,Pakistan,229,2014
48,USA,United States of America,PHL,Philippines,4,2014
49,USA,United States of America,PRK,Dem. People's Rep. of Korea,15,2014
50,USA,United States of America,PSE,Palestinian,140,2014
51,USA,United States of America,RUS,Russian Federation,198,2014
52,USA,United States of America,RWA,Rwanda,51,2014
53,USA,United States of America,SAU,Saudi Arabia,2,2014
54,USA,United States of America,SDN,Sudan,1043,2014
55,USA,United States of America,SGP,Singapore,3,2014
56,USA,United States of America,SLE,Sierra Leone,10,2014
57,USA,United States of America,SOM,Somalia,10057,2014
58,USA,United States of America,SYR,Syrian Arab Rep.,271,2014
59,USA,United States of America,TCD,Chad,31,2014
60,USA,United States of America,TGO,Togo,25,2014
61,USA,United States of America,THA,Thailand,8,2014
62,USA,United States of America,TKM,Turkmenistan,2,2014
63,USA,United States of America,TUN,Tunisia,2,2014
64,USA,United States of America,UGA,Uganda,22,2014
65,USA,United States of America,UKR,Ukraine,667,2014
66,USA,United States of America,UZB,Uzbekistan,65,2014
67,USA,United States of America,VNM,Viet Nam,80,2014
68,USA,United States of America,YEM,Yemen,14,2014
69,USA,United States of America,ZAF,South Africa,3,2014
70,USA,United States of America,ZWE,Zimbabwe,3,2014

In [30]:
resettlment_stats = gis.content.import_data(usa_df, {"Address" : "country_of_origin_en"})

In [31]:
resettlment_stats.query().df

,ObjectId,country_of_asylum,country_of_asylum_en,country_of_origin,country_of_origin_en,value,year,SHAPE
0,1,USA,United States of America,AFG,Afghanistan,696,2014,"{'x': 7349837.296999998, 'y': 4006150.33429999..."
1,2,USA,United States of America,ARM,Armenia,45,2014,"{'x': 5002722.552499998, 'y': 4908624.42499999..."
2,3,USA,United States of America,AZE,Azerbaijan,21,2014,"{'x': 5290871.5066, 'y': 4908197.851800002, 's..."
3,4,USA,United States of America,BDI,Burundi,133,2014,"{'x': 3331396.2041000016, 'y': -370044.6110999..."
4,5,USA,United States of America,BGD,Bangladesh,2,2014,"{'x': 10050864.7128, 'y': 2729624.355900001, '..."
5,6,USA,United States of America,BLR,Belarus,60,2014,"{'x': 3122522.3343, 'y': 7083928.456, 'spatial..."
6,7,USA,United States of America,BTN,Bhutan,7476,2014,"{'x': 10066201.987599999, 'y': 3175395.1653999..."
7,8,USA,United States of America,CAF,Central African Rep.,200,2014,"{'x': -6410163.564099999, 'y': -2919775.608100..."
8,9,USA,United States of America,CHN,China,50,2014,"{'x': 11569437.687399998, 'y': 4378971.0939999..."
9,10,USA,United States of America,CIV,CÃ´te d'Ivoire,39,2014,"{'x': -618349.5579000004, 'y': 851797.52149999..."
10,11,USA,United States of America,CMR,Cameroon,9,2014,"{'x': 1417973.1237999983, 'y': 632475.05799999..."
11,12,USA,United States of America,COD,Dem. Rep. of the Congo,5128,2014,"{'x': 2628888.2291, 'y': -318749.5758000016, '..."
12,13,USA,United States of America,COG,Congo,58,2014,"{'x': 1695985.2120000012, 'y': -91481.61540000..."
13,14,USA,United States of America,COL,Colombia,461,2014,"{'x': -8134755.827500001, 'y': 434606.15190000..."
14,15,USA,United States of America,CUB,Cuba,3703,2014,"{'x': -8849899.5181, 'y': 2511525.2347999997, ..."
15,16,USA,United States of America,ECU,Ecuador,23,2014,"{'x': -8769219.4427, 'y': -159073.81720000133,..."
16,17,USA,United States of America,EGY,Egypt,17,2014,"{'x': 3325168.2776000015, 'y': 3062667.8011000..."
17,18,USA,United States of America,ERI,Eritrea,1409,2014,"{'x': 4325949.652600002, 'y': 1731046.95989999..."
18,19,USA,United States of America,ETH,Ethiopia,687,2014,"{'x': 4413233.397100002, 'y': 963111.951699998..."
19,20,USA,United States of America,GAB,Gabon,3,2014,"{'x': 1311539.5117000006, 'y': -69454.05469999..."
20,21,USA,United States of America,GBR,United Kingdom of Great Britain and Northern I...,1,2014,"{'x': -219250.36549999937, 'y': 7058898.565099..."
21,22,USA,United States of America,GEO,Georgia,15,2014,"{'x': -9289003.079, 'y': 3848717.4228999987, '..."
22,23,USA,United States of America,GHA,Ghana,2,2014,"{'x': -139124.02070000023, 'y': 891327.3944000..."
23,24,USA,United States of America,GIN,Guinea,10,2014,"{'x': -1218113.6270999983, 'y': 1168144.863400..."
24,25,USA,United States of America,GMB,Gambia,1,2014,"{'x': -1712198.5797999986, 'y': 1510963.021800..."
25,26,USA,United States of America,HTI,Haiti,4,2014,"{'x': -8061386.829299999, 'y': 2154935.9151000..."
26,27,USA,United States of America,IDN,Indonesia,18,2014,"{'x': 12681056.085099999, 'y': -110191.5372000..."
27,28,USA,United States of America,IND,India,23,2014,"{'x': 8843590.6582, 'y': 2677963.1317000017, '..."
28,29,USA,United States of America,IRN,Iran (Islamic Rep. of),2830,2014,"{'x': 4481939.772300001, 'y': 5004042.44370000..."
29,30,USA,United States of America,IRQ,Iraq,20337,2014,"{'x': 4873252.5419000015, 'y': 3900478.3422999..."
...,...,...,...,...,...,...,...,...
40,41,USA,United States of America,LKA,Sri Lanka,68,2014,"{'x': 8983330.668499999, 'y': 850505.467399999..."
41,42,USA,United States of America,MAR,Morocco,1,2014,"{'x': -556597.4539999999, 'y': 3763310.6270999..."
42,43,USA,United States of America,MKD,The former Yugoslav Rep. of Macedonia,241,2014,"{'x': 2417361.396899998, 'y': 5102847.34139999..."
43,44,USA,United States of America,MLI,Mali,2,2014,"{'x': -391897.11290000007, 'y': 1963118.469799..."
44,45,USA,United States of America,MMR,Myanmar,15971,2014,"{'x': 10743654.047200002, 'y': 2406783.7716000..."
45,46,USA,United States of America,MRT,Mauritania,4,2014,"{'x': -1150096.0623000003, 'y': 2303798.607999..."
46,47,USA,United States of America,NPL,Nepal,126,2014,"{'x': 9344621.5324, 'y': 3281684.584399998, 's..."
47,48,USA,United States of America,PAK,Pakistan,229,2014,"{'x': 7815752.985599998, 'y': 3544012.30030000..."
48,49,USA,United States of America,PHL,Philippines,4,2014,"{'x': 13454255.108, 'y': 1593137.6396999992, '..."
49,50,USA,United States of America,PRK,Dem. People's Rep. of Korea,15,2014,"{'x': 2061977.6070999987, 'y': 5229636.7884000..."
50,51,USA,United States of America,PSE,Palestinian,140,2014,"{'x': 3918967.5766000003, 'y': 3751859.3574, '..."
51,52,USA,United States of America,RUS,Russian Federation,198,2014,"{'x': 10776324.665199999, 'y': 8856659.7117, '..."
52,53,USA,United States of America,RWA,Rwanda,51,2014,"{'x': 3334721.4657999985, 'y': -222505.4270999..."
53,54,USA,United States of America,SAU,Saudi Arabia,2,2014,"{'x': 4959152.743799999, 'y': 2768204.5044, 's..."
54,55,USA,United States of America,SDN,Sudan,1043,2014,"{'x': 3340607.6521999985, 'y': 1810890.7159999..."
55,56,USA,United States of America,SGP,Singapore,3,2014,"{'x': 11556800.932999998, 'y': 150678.71040000..."
56,57,USA,United States of America,SLE,Sierra Leone,10,2014,"{'x': -1312682.9730999991, 'y': 956238.6911999..."
57,58,USA,United States of America,SOM,Somalia,10057,2014,"{'x': 5143306.1217, 'y': 490803.27809999883, '..."
58,59,USA,United States of America,TCD,Chad,31,2014,"{'x': 2078798.6218999997, 'y': 1732601.8244000..."
59,60,USA,United States of America,TGO,Togo,25,2014,"{'x': 108474.61699999869, 'y': 954101.21429999..."
60,61,USA,United States of America,THA,Thailand,8,2014,"{'x': 11244631.0323, 'y': 1702664.9294999987, ..."
61,62,USA,United States of America,TKM,Turkmenistan,2,2014,"{'x': 6587359.0243999995, 'y': 4749406.4403999..."
62,63,USA,United States of America,TUN,Tunisia,2,2014,"{'x': 1069615.1636000015, 'y': 4044431.4042000..."
63,64,USA,United States of America,UGA,Uganda,22,2014,"{'x': 3599594.3988000005, 'y': 168535.68769999..."
64,65,USA,United States of America,UKR,Ukraine,667,2014,"{'x': 3492640.7919000015, 'y': 6279426.7185000..."
65,66,USA,United States of America,UZB,Uzbekistan,65,2014,"{'x': 7060091.7223000005, 'y': 5098471.8944000..."
66,67,USA,United States of America,VNM,Viet Nam,80,2014,"{'x': 12003951.386100002, 'y': 1824032.1678000..."
67,68,USA,United States of America,YEM,Yemen,14,2014,"{'x': 5298134.5711, 'y': 1793747.6873000003, '..."
68,69,USA,United States of America,ZAF,South Africa,3,2014,"{'x': 2792454.985800002, 'y': -3375287.4081999..."
69,70,USA,United States of America,ZWE,Zimbabwe,3,2014,"{'x': 3326702.470400002, 'y': -2156843.9395999..."

In [32]:
usa_sdf = resettlment_stats.query().df

In [33]:
reset_map = gis.content.import_data(usa_sdf, title='UNHCR Resettlements in USA')

In [34]:
usa_map = gis.map()
usa_map

MapView(basemaps=['dark-gray', 'dark-gray-vector', 'gray', 'gray-vector', 'hybrid', 'national-geographic', 'ocâ¦

In [35]:
usa_map.add_layer(reset_map,  { "renderer":"ClassedSizeRenderer", "field_name":"value" })